### ISSUE TITLE
installing pladipus

### ISSUE THREAD

**Issue by vladie0** [compomics/pladipus#3]
Dear developer, 

Upon Installing Pladipus I've encoutered the following error (during installation):

Could not connect to the database:
no suitable driver found for jdbc

Using Ubuntu 16.04
Version 8 Update 91
mysql  Ver 14.14 Distrib 5.7.12, for Linux (x86_64) using  EditLine wrapper

General solution found on the internet consist of adding a ClassPath to the java code, which i'm unable to perform unless I adjust the code. 

Would you happen to have a solution for this problem ? 
Thanks in advance, 
Volodimir Olexiouk

**Comment by kverhegg** [comment]
Hi Volodimir !

I will definitely look into this. Could you provide me with a stacktrace if possible?
Thanks in advance,

Cheers,

Kenneth

**Comment by vladie0** [comment]
Hi Kenneth, 

trace: 
java.sql.SQLException: No suitable driver found for jdbc:mysql://0.0.0.0:3306                                                                                                                                                                                                  
        at java.sql.DriverManager.getConnection(DriverManager.java:689)                                                                                                                                                                                                        
        at java.sql.DriverManager.getConnection(DriverManager.java:247)                                                                                                                                                                                                        
        at com.compomics.pladipus.view.MySQLPanel.testConnection(MySQLPanel.java:297)                                                                                                                                                                                          
        at com.compomics.pladipus.view.MySQLPanel.btnTestConnectionActionPerformed(MySQLPanel.java:283)                                                                                                                                                                        
        at com.compomics.pladipus.view.MySQLPanel.access$200(MySQLPanel.java:15)                                                                                                                                                                                               
        at com.compomics.pladipus.view.MySQLPanel$3.actionPerformed(MySQLPanel.java:145)                                                                                                                                                                                       
        at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)                                                                                                                                                                                            
        at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)                                                                                                                                                                                        
        at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)                                                                                                                                                                                     
        at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)                                                                                                                                                                                              
        at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)                                                                                                                                                                              
        at java.awt.Component.processMouseEvent(Component.java:6535)                                                                                                                                                                                                           
        at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)                                                                                                                                                                                                      
        at java.awt.Component.processEvent(Component.java:6300)                                                                                                                                                                                                                
        at java.awt.Container.processEvent(Container.java:2236)                                                                                                                                                                                                                
        at java.awt.Component.dispatchEventImpl(Component.java:4891)                                                                                                                                                                                                           
        at java.awt.Container.dispatchEventImpl(Container.java:2294)                                                                                                                                                                                                           
        at java.awt.Component.dispatchEvent(Component.java:4713)                                                                                                                                                                                                               
        at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)                                                                                                                                                                                              
        at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
        at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
        at java.awt.Container.dispatchEventImpl(Container.java:2280)
        at java.awt.Window.dispatchEventImpl(Window.java:2750)
        at java.awt.Component.dispatchEvent(Component.java:4713)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.awt.EventQueue$4.run(EventQueue.java:731)
        at java.awt.EventQueue$4.run(EventQueue.java:729)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by vladie0** [comment]
Furthermore, 
If I skip the installer steps and try to create an account for server use, I get the following error:

Could not create user:
com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent succesfully to the server was 0 milliseconds ago. The driver has not recieved any packets from the server.

I'll check whether installation on windows works well,
Regards, 
vladimir

**Comment by kverhegg** [comment]
Sorry for the late reply. I have released a new version of pladipus just today.
Judging from the error, could you verify the network configuration file in [user home]/pladipus/config ? 
Try changing the db.host property from 0.0.0.0 into localhost (or the actual IP your machine has currently).

Please let me know how it turns out !

Cheers,

Kenneth

**Comment by vladie0** [comment]
Hi Kenneth, 

Apologies for the late reply, I had some other projects which had priority I will now devote my time on making Pladipus work for sORFs.org

Couple of issues I ran into:
- some editing of the parameters was necessary (mainly with the ports) as the installers made available on the website still contain, what I assume to be, your test parameters (network.properties file)
-attempting to install Pladipus manager provides the following error (ActiveMQ and MySQL working correctly):

 Exception in thread "Thread-4" java.lang.NoClassDefFoundError: Could not initialize class net.jimmc.jshortcut.JShellLink
        at com.compomics.pladipus.controller.setup.InstallPladipus.createDesktopIcon(InstallPladipus.java:109)
        at com.compomics.pladipus.controller.setup.InstallPladipus.installConsole(InstallPladipus.java:98)
        at com.compomics.pladipus.view.PladipusPanel$4.run(PladipusPanel.java:153)
        at java.lang.Thread.run(Thread.java:745)

-Manual installation of Pladipus runs into the following error:

16:20:26,105 ERROR InstallPladipus:194 - com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'pladipus.users' doesn't exist


- Next I attempted to recreate the database architecture manually following the source code, some things I've noticed:
a database PLADIPUS was created as stated in the source code, however the software looks for the pladipus database (lower case). As unix is case sensitive (I believe MySQL in windows is not), perhaps this could be the issue ? re-creating the database in lower case did solve the login issue, however I immediately get the following error:

vladie@vladie-GE60-0NC-GE60-0ND:~/Desktop/pladipus$ java -jar Pladipus-execution-1.2.0/Pladipus-execution-1.2.0.jar 
Exception in thread "AWT-EventQueue-0" org.jasypt.exceptions.EncryptionOperationNotPossibleException
        at org.jasypt.digest.StandardByteDigester.matches(StandardByteDigester.java:1107)
        at org.jasypt.digest.StandardStringDigester.matches(StandardStringDigester.java:1052)
        at org.jasypt.util.password.StrongPasswordEncryptor.checkPassword(StrongPasswordEncryptor.java:99)
        at com.compomics.pladipus.core.control.distribution.service.UserService.isCorrectPassword(UserService.java:85)
        at com.compomics.pladipus.core.control.distribution.service.UserService.verifyUser(UserService.java:80)
        at com.compomics.pladipus.view.dialogs.LoginDialog.login(LoginDialog.java:234)
        at com.compomics.pladipus.view.dialogs.LoginDialog.btnLoginActionPerformed(LoginDialog.java:255)
        at com.compomics.pladipus.view.dialogs.LoginDialog.access$100(LoginDialog.java:20)
        at com.compomics.pladipus.view.dialogs.LoginDialog$3.actionPerformed(LoginDialog.java:138)
        at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
        at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
        at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
        at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
        at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
        at java.awt.Component.processMouseEvent(Component.java:6535)
        at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
        at java.awt.Component.processEvent(Component.java:6300)
        at java.awt.Container.processEvent(Container.java:2236)
        at java.awt.Component.dispatchEventImpl(Component.java:4891)
        at java.awt.Container.dispatchEventImpl(Container.java:2294)
        at java.awt.Component.dispatchEvent(Component.java:4713)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
        at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
        at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
        at java.awt.Container.dispatchEventImpl(Container.java:2280)
        at java.awt.Window.dispatchEventImpl(Window.java:2750)
        at java.awt.Component.dispatchEvent(Component.java:4713)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.awt.EventQueue$4.run(EventQueue.java:731)
        at java.awt.EventQueue$4.run(EventQueue.java:729)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
        at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:184)
        at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:229)
        at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:227)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:227)
        at java.awt.Dialog.show(Dialog.java:1084)
        at java.awt.Component.show(Component.java:1673)
        at java.awt.Component.setVisible(Component.java:1625)
        at java.awt.Window.setVisible(Window.java:1014)
        at java.awt.Dialog.setVisible(Dialog.java:1005)
        at com.compomics.pladipus.view.MainGUI.<init>(MainGUI.java:68)
        at com.compomics.pladipus.view.MainGUI$10.run(MainGUI.java:348)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82

I suspect the password created are encrypted, so manually creating an password (without encryption) causes problems. Enforcing you password encryption allows me to login correctly without errors into Pladipus ! 

With the database architecture in order, the MySQL and activeMQ working, I retried to use the default installer (just to test), now the installer provides the following error:
Java HotSpot(TM) 64-Bit Server VM warning: You have loaded library /tmp/jshortcut-4598220208465196981.dll which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
Exception in thread "Thread-1" java.lang.UnsatisfiedLinkError: /tmp/jshortcut-4598220208465196981.dll: /tmp/jshortcut-4598220208465196981.dll: invalid ELF header (Possible cause: endianness mismatch)
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
        at java.lang.Runtime.load0(Runtime.java:809)
        at java.lang.System.load(System.java:1086)
        at net.jimmc.jshortcut.JShellLink.<clinit>(JShellLink.java:128)
        at com.compomics.pladipus.controller.setup.InstallPladipus.createDesktopIcon(InstallPladipus.java:109)
        at com.compomics.pladipus.controller.setup.InstallPladipus.installConsole(InstallPladipus.java:98)
        at com.compomics.pladipus.view.PladipusPanel$4.run(PladipusPanel.java:153)
        at java.lang.Thread.run(Thread.java:745)

I'll proceed testing Pladipus for sORFs.org. One more request: may I create a Fork of your pladipus to create an adaptation for sORFs.org and how exactly do I convert your source code into a working "jar" file ? 

Thanks in advance, 
Volodimir Olexiouk
